FROM node:18-alpine

WORKDIR /app

# Copy package.json
COPY apps/frontend/package.json .

# Install dependencies
RUN npm install

# Copy frontend code
COPY apps/frontend /app

# Expose port
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
